version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "stable"
  jobs:
    post_create_environment:
      # Copy documentation files to docs/ directory for MkDocs
      - cp README.md docs/index.md
      - cp API_REFERENCE.md docs/API_REFERENCE.md
      - cp CONTRIBUTING.md docs/CONTRIBUTING.md
    post_build:
      # Build Rust documentation
      - cargo doc --no-deps --target-dir target/doc
      # Create directory for Rust docs in the HTML output
      - mkdir -p $READTHEDOCS_OUTPUT/html/rust_docs
      # Copy Rust docs to the output directory
      - cp -r target/doc/* $READTHEDOCS_OUTPUT/html/rust_docs/

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
